/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author sax
 */
public class ViewCaesar extends javax.swing.JPanel {

    /**
     * Creates new form ViewCaesar
     */
    public ViewCaesar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btng_cypher = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_message = new javax.swing.JTextArea();
        jrb_encrypt = new javax.swing.JRadioButton();
        jrb_decrypt = new javax.swing.JRadioButton();
        jbnt_execute = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jta_message.setColumns(20);
        jta_message.setRows(5);
        jScrollPane1.setViewportView(jta_message);

        jrb_encrypt.setBackground(new java.awt.Color(255, 255, 255));
        btng_cypher.add(jrb_encrypt);
        jrb_encrypt.setSelected(true);
        jrb_encrypt.setText("Cifrar");

        jrb_decrypt.setBackground(new java.awt.Color(255, 255, 255));
        btng_cypher.add(jrb_decrypt);
        jrb_decrypt.setText("Descifrar");

        jbnt_execute.setBackground(new java.awt.Color(255, 255, 255));
        jbnt_execute.setText("Cifrar");
        jbnt_execute.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_encrypt)
                    .addComponent(jrb_decrypt))
                .addGap(84, 84, 84)
                .addComponent(jbnt_execute, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrb_encrypt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_decrypt))
                    .addComponent(jbnt_execute, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btng_cypher;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbnt_execute;
    public javax.swing.JRadioButton jrb_decrypt;
    public javax.swing.JRadioButton jrb_encrypt;
    public javax.swing.JTextArea jta_message;
    // End of variables declaration//GEN-END:variables
}
